--- #YAML:1.0
name:               feedGnuplot
version:            1.13
abstract:           A pipe-oriented frontend to Gnuplot
author:
    - Dima Kogan <dkogan@cds.caltech.edu>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Script::Run:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
