---
abstract: unknown
author:
  - 'Dima Kogan <dima@secretsauce.net>'
build_requires:
  IPC::Run: 0
  String::ShellQuote: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: feedgnuplot
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.30
